from typing import Dict, List

import numpy as np
from numpy import floating, datetime64
from numpy.typing import NDArray

from astropy import units as u
from astropy.time import TimeDelta
from astropy.timeseries import TimeSeries

from plotly.graph_objects import Figure, Scatter


def plot_lightcurve(
        lightcurve: TimeSeries,
        time_units: u.UnitBase = u.day,
        rate_units: u.UnitBase = u.second**-1,
        observations_only: bool = False,
        title: str|None = None,
        period: TimeDelta|str|None = None,
) -> Figure:
    """
    Given a lightcurve, plots it (with uncertainty regions).

    :param lightcurve: The lightcurve table to plot
    :param title: The title for the plot
    :param time_units: What units to show the time axis in, default days
    :param rate_units: What units to show the count rate in, default per second
    :param observations_only: Whether to show the actual observations only
    :param title: The title for the plot. If left blank, autogenerated from the table metadata.
    :param period: The period of oscillation. If 'auto', autogenerated; if false, not shown.
    :return: The plotted figure
    """
    time: NDArray[floating] = lightcurve["time"].jd

    figure: Figure = Figure(
        data=[
            Scatter(
                x=time,
                y=lightcurve["rate"].to(rate_units), showlegend=False,
            ),
            Scatter(
                x=time,
                y=(lightcurve["rate"]+lightcurve["error"]).to(rate_units), showlegend=False,
                line_width=0,
            ),
            Scatter(
                x=time,
                y=(lightcurve["rate"]-lightcurve["error"]).to(rate_units), showlegend=False,
                line_width=0, fill="tonexty", fillcolor="rgba(99,110,250,0.25)",
            )
        ] if not observations_only else [
            Scatter(
                x=time,
                y=lightcurve["rate"].to(rate_units),
                mode="markers",
            )
        ],
        layout={
            "title": title,
            "xaxis_title": f"Time ({time_units})",
            "yaxis_title": f"Count rate ({rate_units})"
        }
    )

    if period:
        if period is 'auto':
            # If we haven't specified otherwise, automatically
            period = lightcurve.meta['model_definition'].get_period()

        periods: NDArray[floating] = np.arange(
            time[0], time[-1], step=period.jd
        )

        figure.layout.xaxis.dtick = period.jd
        # for period in periods:
        #     figure.add_vline(period, line_color="rgba(255, 255, 255, 255)", layer="below")

    return figure
